In [3]:
import numpy as np

# Array Basics + Types

In [4]:
arr = np.arange(1, 21)

print("Array : ", arr)
print("Shape : ", arr.shape)
print("Dtype : ", arr.dtype)
print("Min value : ", arr.min())
print("Max Value : ", arr.max())
print("Sum : ", arr.sum())
print("Mean : ", arr.min())

arr = arr.astype('float64')
print("Array : ", arr)
print("Dtype : ", arr.dtype)

Array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Shape :  (20,)
Dtype :  int64
Min value :  1
Max Value :  20
Sum :  210
Mean :  1
Array :  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
Dtype :  float64


# Slicing + Boolean masking

In [5]:
arr = np.random.randint(1, 101, size=50)

print("Random array : ", arr)

even = arr[arr % 2 == 0]
print("\nEven numbers : ", even)

div_by_3_and_gt_50 = arr[(arr % 3 == 0) & (arr > 50)]
print("\nElements greater that 50 and divisiible by 3 : ", div_by_3_and_gt_50)

replaced = np.where(arr < 20, 20, arr)
print("\nArray after replacing less that 20 values with 20 : ", replaced)

Random array :  [44 93 17 84 27 82 56 47 46 22  5 39 18 10 38 66 51 45  9 63 24  1 22 41
 34 41 72  6 50 35 62 45 53 18  2 30 19 60 76 34  3 99 65 36 13 55 99 68
 26 53]

Even numbers :  [44 84 82 56 46 22 18 10 38 66 24 22 34 72  6 50 62 18  2 30 60 76 34 36
 68 26]

Elements greater that 50 and divisiible by 3 :  [93 84 66 51 63 72 60 99 99]

Array after replacing less that 20 values with 20 :  [44 93 20 84 27 82 56 47 46 22 20 39 20 20 38 66 51 45 20 63 24 20 22 41
 34 41 72 20 50 35 62 45 53 20 20 30 20 60 76 34 20 99 65 36 20 55 99 68
 26 53]


# Reshape + Axis Opeartions

In [6]:
arr = np.arange(1, 61)
arr = arr.reshape(5, 12)

print("Original array : ", arr)

row_sum = arr.sum(axis=1)
print("Row wise Sum : ", row_sum)

col_mean = arr.mean(axis=0)
print("Columns wise mean : ",col_mean)

standard_deviation = arr.std()
print("Standard Deviation : ", standard_deviation)

row, col = np.where(arr == arr.max())
print("Position of max element : ", row, col)

Original array :  [[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56 57 58 59 60]]
Row wise Sum :  [ 78 222 366 510 654]
Columns wise mean :  [25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.]
Standard Deviation :  17.318102282486574
Position of max element :  [4] [11]


# Broadcasting Practice

In [7]:
# (4, 5) matrix of random floats
A = np.random.rand(4, 5)

# (5,) vector
v = np.random.rand(5)

# Adding vector v to every row using broadcasting
B = A + v

# Normalize each row to sum to 1
row_sums = B.sum(axis=1, keepdims=True)

# Avoiding division by zero by replacing 0 with 1
row_sums = np.where(row_sums == 0, 1, row_sums)

B_normalized = B / row_sums

print("Original matrix A:\n", A)
print("\nVector v:\n", v)
print("\nAfter broadcasting addition B:\n", B)
print("\nRow-normalized matrix:\n", B_normalized)
print("\nRow sums (should be 1):\n", B_normalized.sum(axis=1))



Original matrix A:
 [[0.34729146 0.13489751 0.20246985 0.54155229 0.24846962]
 [0.18103167 0.31082307 0.79735529 0.37784315 0.23507507]
 [0.00754089 0.3446225  0.74754687 0.99604461 0.25651554]
 [0.62302568 0.61366689 0.22616118 0.58586127 0.28662094]]

Vector v:
 [0.11723682 0.28504078 0.08979652 0.76564014 0.84533336]

After broadcasting addition B:
 [[0.46452828 0.41993829 0.29226638 1.30719243 1.09380298]
 [0.29826849 0.59586385 0.88715182 1.14348329 1.08040844]
 [0.12477771 0.62966328 0.83734339 1.76168475 1.1018489 ]
 [0.7402625  0.89870767 0.31595771 1.35150141 1.1319543 ]]

Row-normalized matrix:
 [[0.12983889 0.11737568 0.08169049 0.36536939 0.30572555]
 [0.07447076 0.14877345 0.22150134 0.28550139 0.26975306]
 [0.02800647 0.14132847 0.18794245 0.39541167 0.24731094]
 [0.16678651 0.20248535 0.07118756 0.30450306 0.25503751]]

Row sums (should be 1):
 [1. 1. 1. 1.]


# Matrix Ops (Transpose, Identity, Dot)

In [8]:
# Generate matrices
A = np.random.rand(3, 4)
B = np.random.rand(4, 2)

# Computing matrix product A @ B
C = A @ B

# Verifying transpose property
transpose_check = np.allclose((A.T).T, A)

# Create identity matrix and verify A @ I = A (shape permitting)
I = np.eye(4)
A_identity = A @ I

print("Matrix A (3x4):\n", A)
print("\nMatrix B (4x2):\n", B)
print("\nA @ B (3x2):\n", C)

print("\n(A.T).T equals A:", transpose_check)

print("\nIdentity matrix I (4x4):\n", I)
print("\nA @ I:\n", A_identity)
print("\nA @ I equals A:", np.allclose(A_identity, A))


Matrix A (3x4):
 [[0.03490914 0.33111258 0.9662027  0.18951783]
 [0.75083955 0.53769605 0.6318492  0.17667179]
 [0.12546075 0.40708665 0.7857753  0.03807231]]

Matrix B (4x2):
 [[0.66142965 0.43739215]
 [0.88823535 0.20183938]
 [0.17847791 0.78777792]
 [0.97241762 0.40807914]]

A @ B (3x2):
 [[0.67393215 0.92059196]
 [1.25879807 1.00679249]
 [0.62183794 0.77159462]]

(A.T).T equals A: True

Identity matrix I (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

A @ I:
 [[0.03490914 0.33111258 0.9662027  0.18951783]
 [0.75083955 0.53769605 0.6318492  0.17667179]
 [0.12546075 0.40708665 0.7857753  0.03807231]]

A @ I equals A: True


# Fancy Indexing + Scatter Updates

In [9]:
arr = np.zeros(30, dtype=int)

indices = np.random.choice(30, size=8, replace=False)
arr[indices] = 1 # fancy indexing or scatter updates (this updates all the indices at once with 1)

# Set positions divisible by 5 to 9 (overwrite if needed)
arr[::5] = 9

print("Randomly chosen indices:", indices)
print("Final array:\n", arr)


Randomly chosen indices: [17  7 14  6 27 28  0 15]
Final array:
 [9 0 0 0 0 9 1 1 0 0 9 0 0 0 1 9 0 1 0 0 9 0 0 0 0 9 0 1 1 0]


# Sorting + Top-k without Sort

In [10]:
arr = np.random.rand(100)

k = 10

# Get indices of top-k elements
topk_idx = np.argpartition(arr, -k)[-k:]

# Sort those top-k indices by value (descending)
top_elements = arr[topk_idx]
sorted_topk_idx = topk_idx[np.argsort(top_elements)[::-1]]

topk_values = arr[sorted_topk_idx]

print("Top 10 values:")
for i, v in zip(sorted_topk_idx, topk_values):
    print(f"Index: {i:3d}, Value: {v:.6f}")




Top 10 values:
Index:  67, Value: 0.996092
Index:  41, Value: 0.966457
Index:   0, Value: 0.963026
Index:  30, Value: 0.959792
Index:  48, Value: 0.957405
Index:  12, Value: 0.948547
Index:  34, Value: 0.945465
Index:  17, Value: 0.944112
Index:  42, Value: 0.941630
Index:  18, Value: 0.928427


# Missing Value Simulation

In [11]:
arr = np.random.rand(40)

num_missing = int(0.2 * arr.size)  # 20% of 40 = 8
missing_indices = np.random.choice(arr.size, size=num_missing, replace=False)
arr[missing_indices] = np.nan

mean_val = np.nanmean(arr)

median_val = np.nanmedian(arr)
arr[np.isnan(arr)] = median_val

print("Indices of NaNs:", missing_indices)
print("Mean ignoring NaNs:", mean_val)
print("Median used to replace NaNs:", median_val)
print("Array after filling NaNs:\n", arr)


Indices of NaNs: [15 20 17 29  6 28 39 34]
Mean ignoring NaNs: 0.4366270615571537
Median used to replace NaNs: 0.36948154631701263
Array after filling NaNs:
 [0.3553997  0.1828672  0.16435497 0.12130515 0.52967124 0.7303123
 0.36948155 0.95201608 0.73196823 0.33882041 0.13847413 0.27743909
 0.13983236 0.85676369 0.38351159 0.36948155 0.11804556 0.36948155
 0.3554515  0.56000875 0.36948155 0.50542464 0.56973037 0.73854594
 0.98569532 0.9439012  0.80831492 0.27359509 0.36948155 0.36948155
 0.64185983 0.22938512 0.01679697 0.06498937 0.36948155 0.32479854
 0.12632564 0.41311886 0.39334221 0.36948155]


# Linear Regression From Scratch

In [12]:
n_samples = 200

X = np.random.rand(n_samples, 1)

noise = np.random.randn(n_samples, 1) * 0.5

y = 3 * X + 5 + noise

X_design = np.hstack([
    np.ones((n_samples, 1)),
    X
])

# Normal Equation
#    theta = (X^T X)^(-1) X^T y
theta = np.linalg.inv(
    X_design.T @ X_design
) @ X_design.T @ y


intercept = theta[0, 0]
slope = theta[1, 0]

print(f"Estimated intercept: {intercept:.4f}")
print(f"Estimated slope: {slope:.4f}")


Estimated intercept: 4.9641
Estimated slope: 3.0092


# Time Series Rolling Window Stats

In [13]:
n_days = 365

sales = np.random.normal(loc=100, scale=15, size=n_days)


def rolling_window(arr, window):
    """
    Create rolling window view of a 1D array
    """
    shape = (arr.size - window + 1, window)
    strides = (arr.strides[0], arr.strides[0])
    return np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)

roll7 = rolling_window(sales, 7)
rolling_7_mean = np.full(n_days, np.nan)
rolling_7_mean[6:] = roll7.mean(axis=1)

roll30 = rolling_window(sales, 30)

rolling_30_mean = np.full(n_days, np.nan)
rolling_30_std = np.full(n_days, np.nan)

rolling_30_mean[29:] = roll30.mean(axis=1)
rolling_30_std[29:] = roll30.std(axis=1)

anomalies = (
    sales > (rolling_30_mean + 2 * rolling_30_std)
)

anomaly_days = np.where(anomalies)[0]

print(f"Total anomaly days detected: {len(anomaly_days)}")
print("First 10 anomaly day indices:", anomaly_days[:10])


Total anomaly days detected: 6
First 10 anomaly day indices: [ 40 108 134 200 292 353]
